# -*- coding: utf-8 -*-
"""EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tme0bl_k1ynIWb6fY2gzE-JzAhwXn1ZW

###Name : Ayush Phale
###PRN : 25070123028
###Batch : ENTC A2
##Unit 1
#Basics of python - Experiment -1
"""

#First Python program/string
print("hello,welcome to Python Programming")

a= "Hello"
print(a)

#This is a Comment

print("hello");print("How are you");print("Bye bye!")

#Print numbers
a=3
print(a)
print(358)
print(500.200)

#Variables
x=5
y="Hello,World!"
print(x)
print(y)

#Case-sensitive
a=4
A="Sally"
print(a)
print(A)

#Many values to multiple variables
x,y,z="Orange","Banana","Cherry"
print(x)
print(y)
print(z)

#Basic Arithmetic Operations
a = 10
b = 5
print("Addition=",a+b)

#Understanding Data Types
x=10
y=3.14
z="Python"
A= True
c= 3+2j
print(type(x))
print(type(y))
print(type(z))
print(type(A))
print(type(c))

#Taking Input from User
name = input("Enter Your Name:")
age = int(input("Enter our age:"))
print("Name:", name)
print("Age:",age)

#Problem statements
#1. Take marks of  subjects and find the sum and avg
#2. Find area of circle
#3. Find area and perimeter of rectangle

#1. Take marks of  subjects and find the sum and avg
a = int(input("Enter marks of first subject:"))
b = int(input("Enter marks of second subject:"))
c = int(input("Enter marks of thirdsubject:"))
d = int(input("Enter marks of fourth subject:"))
e = int(input("Enter marks of fifth subject:"))
x= a+b+c+d+e
y= x/5
print("Sum=",x)
print("Average=",y)

#2. Find area of circle
r = float(input("Radius of the circle:"))
A= 3.14*r*r
print("Area of circle=",A)

#3. Find area and perimeter of rectangle
a = int(input("Enter length:"))
b = int(input("Enter breadth:"))
P = 2*(a+b)
A= a*b
print("Perimeter of rectangle",P)
print("Area of rectangle",A)

#Simple Calculator
a=int(input("Enter first number:"))
b=int(input("Enter Second number:"))
sum=a+b
print("product",a*b)
print("division=",a/b)
print("substraction=",a-b)

#Python Booleans
print(10>9)
print(10==9)
print(10<9)

#Print a mesasge based on whether the condition is True or Flase